import {
    attribute,
    autoGeneratedHashKey,
    table
} from '@aws/dynamodb-data-mapper-annotations';
import { Models } from 'utilities-techsweave';

/*
 * This class rappresent a product item in products table
 */
@table(process.env.TAGS_TABLE)
class Tag implements Models.Tables.ITag {
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    name: string;

    @attribute()
    description: string;
}

export default Tag;